In [9]:
!python Week10Dataset_process.py

class_idx:  13
number: 182
all_idx:  range(0, 182)
val_number:  36
val_idx:  [98, 107, 10, 66, 130, 124, 103, 77, 122, 91, 149, 55, 129, 35, 72, 168, 24, 158, 64, 136, 154, 37, 79, 25, 18, 84, 120, 143, 164, 90, 111, 80, 52, 141, 173, 113]
146
normMean = [139.46329485 131.12781297 125.90959682]
normStd = [53.99856498 54.46404513 56.27036994]
w, h:  [500, 331]
w, h:  [500, 331]
 ********* img_0 *********
torch.Size([1, 3, 448, 448])
tensor([[[[-136.0000, -136.0000, -136.0000,  ..., -137.0000, -137.0000,
           -137.0000],
          [-136.0000, -136.0000, -136.0000,  ..., -137.0000, -137.0000,
           -137.0000],
          [-136.0000, -136.0000, -136.0000,  ..., -137.0000, -137.0000,
           -137.0000],
          ...,
          [-136.9420, -136.0000, -135.7098,  ...,   74.0000,   74.0000,
             74.0000],
          [-136.9420, -136.0000, -135.7098,  ...,   74.0000,   74.0000,
             74.0000],
          [-136.9420, -136.0000, -135.7098,  ...,   74.0000,   74.0000,
  

In [5]:
!python train.py

conv1.weight
yes
bn1.weight
yes
bn1.bias
yes
bn1.running_mean
yes
bn1.running_var
yes
bn1.num_batches_tracked
yes
layer1.0.conv1.weight
yes
layer1.0.bn1.weight
yes
layer1.0.bn1.bias
yes
layer1.0.bn1.running_mean
yes
layer1.0.bn1.running_var
yes
layer1.0.bn1.num_batches_tracked
yes
layer1.0.conv2.weight
yes
layer1.0.bn2.weight
yes
layer1.0.bn2.bias
yes
layer1.0.bn2.running_mean
yes
layer1.0.bn2.running_var
yes
layer1.0.bn2.num_batches_tracked
yes
layer1.0.conv3.weight
yes
layer1.0.bn3.weight
yes
layer1.0.bn3.bias
yes
layer1.0.bn3.running_mean
yes
layer1.0.bn3.running_var
yes
layer1.0.bn3.num_batches_tracked
yes
layer1.0.downsample.0.weight
yes
layer1.0.downsample.1.weight
yes
layer1.0.downsample.1.bias
yes
layer1.0.downsample.1.running_mean
yes
layer1.0.downsample.1.running_var
yes
layer1.0.downsample.1.num_batches_tracked
yes
layer1.1.conv1.weight
yes
layer1.1.bn1.weight
yes
layer1.1.bn1.bias
yes
layer1.1.bn1.running_mean
yes
layer1.1.bn1.running_var
yes
layer1.1.bn1.num_batches_tracke

Epoch 1/100: 100%|█| 73/73 [02:20<00:00,  1.93s/it, average_loss=915, loss_cls=5
Epoch 2/100: 100%|█| 73/73 [02:18<00:00,  1.90s/it, average_loss=853, loss_cls=1
Epoch 3/100: 100%|█| 73/73 [02:18<00:00,  1.90s/it, average_loss=833, loss_cls=3
Epoch 4/100: 100%|█| 73/73 [02:19<00:00,  1.91s/it, average_loss=819, loss_cls=5
Epoch 5/100: 100%|█| 73/73 [02:18<00:00,  1.90s/it, average_loss=809, loss_cls=4
Epoch 6/100: 100%|█| 73/73 [05:27<00:00,  4.49s/it, average_loss=798, loss_cls=8
Epoch 7/100: 100%|█| 73/73 [03:20<00:00,  2.74s/it, average_loss=789, loss_cls=6
Epoch 8/100: 100%|█| 73/73 [02:27<00:00,  2.03s/it, average_loss=782, loss_cls=4
Epoch 9/100: 100%|█| 73/73 [06:20<00:00,  5.21s/it, average_loss=774, loss_cls=9
Epoch 10/100: 100%|█| 73/73 [02:17<00:00,  1.89s/it, average_loss=766, loss_cls=
Epoch 11/100: 100%|█| 73/73 [05:01<00:00,  4.13s/it, average_loss=753, loss_cls=
Epoch 12/100: 100%|█| 73/73 [03:22<00:00,  2.77s/it, average_loss=743, loss_cls=
Epoch 13/100: 100%|█| 73/73 

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [1]:
!jupyter notebook --NotebookApp.iopub_msg_rate_limit=100000

[I 15:02:34.305 NotebookApp] Writing notebook server cookie secret to /home/stu_17685590730/.local/share/jupyter/runtime/notebook_cookie_secret
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/jupyter_core/application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "</opt/conda/lib/python3.7/site-packages/decorator.py:decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/notebook/notebookapp.py", line 1769, in initialize
    self.init_webapp()
  File "/opt/conda/lib/python3.7/site-packages/not

In [2]:
!ls

Week10Dataset_process.py  main.py		  train.py
__pycache__		  object_detection.ipynb  week10_dataset
ground_true.py		  output		  yolo_v1_loss.py
input			  predict_decoder.py
kmeans_for_anchors.py	  resnet_yolo_v1.py


In [7]:
!jupyter notebook --generate-config

Writing default config to: /home/stu_17685590730/.jupyter/jupyter_notebook_config.py


In [2]:
!python train.py

Epoch 151/200: 100%|█| 73/73 [01:22<00:00,  1.14s/it, average_loss=0.28, loss_cl
get best test loss 0.28050
Epoch 152/200: 100%|█| 73/73 [01:21<00:00,  1.12s/it, average_loss=0.3, loss_cls
Epoch 153/200: 100%|█| 73/73 [01:23<00:00,  1.15s/it, average_loss=0.286, loss_c
Epoch 154/200: 100%|█| 73/73 [01:24<00:00,  1.16s/it, average_loss=0.297, loss_c
Epoch 155/200: 100%|█| 73/73 [01:22<00:00,  1.13s/it, average_loss=0.41, loss_cl
Epoch 156/200: 100%|█| 73/73 [01:22<00:00,  1.12s/it, average_loss=0.282, loss_c
Epoch 157/200: 100%|█| 73/73 [01:22<00:00,  1.13s/it, average_loss=0.291, loss_c
Epoch 158/200: 100%|█| 73/73 [01:22<00:00,  1.13s/it, average_loss=0.301, loss_c
Epoch 159/200: 100%|█| 73/73 [01:20<00:00,  1.10s/it, average_loss=0.274, loss_c
get best test loss 0.27364
Epoch 160/200: 100%|█| 73/73 [01:21<00:00,  1.11s/it, average_loss=0.284, loss_c
Epoch 161/200: 100%|█| 73/73 [01:22<00:00,  1.13s/it, average_loss=0.288, loss_c
Epoch 162/200: 100%|█| 73/73 [01:24<00:00,  1.16s/it, a

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [3]:
!python predict_decoder.py

img name=week10_dataset/image/guozhiwei/7.jpg
predict_decoder.py:265: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  img = Variable(img[None, :, :, :], volatile=True)
pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor_h: tensor([[ 5.0000],
        [11.9688]])
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[7,7,1]==1
box.size: torch.Size([4])
get a box
tensor([0.3846, 0.0979, 0.6763, 0.9410])
the box cls=
tensor(13)
the box max_prob
tensor(0.1551)
the box contain_prob
tensor([0.8818])
float((contain_prob*max_prob)[0])
0.13675031065940857
find a box (7 7 1)
cls_indexs_len=1
tensor([0])
[0]
[0]
1
get i: 0
index[0] ious=
tensor([], size=(1, 0))
[]
[0]
############## write file ./input/detection-results/guozhiwei7.txt##############
img name=week10_dataset/image/guozhiwei/8.jpg
pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor

pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor_h: tensor([[ 5.0000],
        [11.9688]])
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[7,6,1]==1
box.size: torch.Size([4])
get a box
tensor([0.3303, 0.1252, 0.6292, 0.9930])
the box cls=
tensor(13)
the box max_prob
tensor(0.4937)
the box contain_prob
tensor([0.7751])
float((contain_prob*max_prob)[0])
0.38269445300102234
find a box (7 6 1)
cls_indexs_len=1
tensor([0])
[0]
[0]
1
get i: 0
index[0] ious=
tensor([], size=(1, 0))
[]
[0]
############## write file ./input/detection-results/zhaomingmingWechatIMG417.txt##############
img name=week10_dataset/image/zhaomingming/WechatIMG413.png
pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor_h: tensor([[ 5.0000],
        [11.9688]])
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[7,5,1]==1
box.size: torch.Size([4])
get a box
tensor([0.2766, 0

pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor_h: tensor([[ 5.0000],
        [11.9688]])
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[8,5,1]==1
box.size: torch.Size([4])
get a box
tensor([0.1434, 0.1485, 0.6354, 1.0464])
the box cls=
tensor(11)
the box max_prob
tensor(0.9951)
the box contain_prob
tensor([0.2057])
float((contain_prob*max_prob)[0])
0.20467478036880493
find a box (8 5 1)
cls_indexs_len=1
tensor([0])
[0]
[0]
1
get i: 0
index[0] ious=
tensor([], size=(1, 0))
[]
[0]
############## write file ./input/detection-results/zhaomingmingWechatIMG390.txt##############
img name=week10_dataset/image/zhaomingming/WechatIMG438.png
pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor_h: tensor([[ 5.0000],
        [11.9688]])
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[7,7,1]==1
box.size: torch.Size([4])
get a box
tensor([0.3445, 0

pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor_h: tensor([[ 5.0000],
        [11.9688]])
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[6,6,1]==1
box.size: torch.Size([4])
get a box
tensor([ 0.2478, -0.0526,  0.7352,  0.9688])
the box cls=
tensor(13)
the box max_prob
tensor(0.9999)
the box contain_prob
tensor([0.7457])
float((contain_prob*max_prob)[0])
0.7455819249153137
find a box (6 6 1)
cls_indexs_len=1
tensor([0])
[0]
[0]
1
get i: 0
index[0] ious=
tensor([], size=(1, 0))
[]
[0]
############## write file ./input/detection-results/zhangyu微信图片_202007150229589.txt##############


In [4]:
!python main.py

21.67% = 其他 AP 
55.56% = 农夫山泉 AP 
50.00% = 冰露 AP 
50.00% = 可口可乐 AP 
12.72% = 天府可乐 AP 
16.67% = 娃哈哈 AP 
0.00% = 康师傅 AP 
25.00% = 怡宝 AP 
16.67% = 苏打水 AP 
mAP = 27.59%
Figure(640x480)


In [10]:
!python predict_decoder.py

img name=week10_dataset/image/guozhiwei/7.jpg
predict_decoder.py:266: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  img = Variable(img[None, :, :, :], volatile=True)
pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor_h: tensor([[ 5.0000],
        [11.9688]])
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[7,7,1]==1
box.size: torch.Size([4])
get a box
tensor([0.3871, 0.1117, 0.6735, 0.9312])
the box cls=
tensor(13)
the box max_prob
tensor(0.3848)
the box contain_prob
tensor([0.8542])
float((contain_prob*max_prob)[0])
0.32867738604545593
find a box (7 7 1)
cls_indexs_len=1
tensor([0])
[0]
[0]
1
get i: 0
index[0] ious=
tensor([], size=(1, 0))
[]
[0]
############## write file ./input/detection-results/guozhiwei7.txt##############
img name=week10_dataset/image/guozhiwei/8.jpg
pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor

[0]
1
get i: 0
index[0] ious=
tensor([], size=(1, 0))
[]
[0]
############## write file ./input/detection-results/zhaomingmingWechatIMG385.txt##############
img name=week10_dataset/image/zhaomingming/WechatIMG417.png
pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor_h: tensor([[ 5.0000],
        [11.9688]])
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[7,6,1]==1
box.size: torch.Size([4])
get a box
tensor([0.3314, 0.1424, 0.6220, 0.9769])
the box cls=
tensor(13)
the box max_prob
tensor(0.5733)
the box contain_prob
tensor([0.4566])
float((contain_prob*max_prob)[0])
0.2617429792881012
find a box (7 6 1)
cls_indexs_len=1
tensor([0])
[0]
[0]
1
get i: 0
index[0] ious=
tensor([], size=(1, 0))
[]
[0]
############## write file ./input/detection-results/zhaomingmingWechatIMG417.txt##############
img name=week10_dataset/image/zhaomingming/WechatIMG413.png
pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750]

pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor_h: tensor([[ 5.0000],
        [11.9688]])
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[7,6,1]==1
box.size: torch.Size([4])
get a box
tensor([0.3315, 0.1298, 0.6217, 0.9391])
the box cls=
tensor(10)
the box max_prob
tensor(0.2180)
the box contain_prob
tensor([0.2908])
float((contain_prob*max_prob)[0])
0.0633855015039444
find a box (7 6 1)
cls_indexs_len=1
tensor([0])
[0]
[0]
1
get i: 0
index[0] ious=
tensor([], size=(1, 0))
[]
[0]
############## write file ./input/detection-results/zhaomingmingWechatIMG386.txt##############
img name=week10_dataset/image/zhaomingming/WechatIMG390.png
pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor_h: tensor([[ 5.0000],
        [11.9688]])
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[8,5,1]==1
box.size: torch.Size([4])
get a box
tensor([0.1460, 0.

pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor_h: tensor([[ 5.0000],
        [11.9688]])
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[6,7,1]==1
box.size: torch.Size([4])
get a box
tensor([0.3589, 0.0625, 0.6981, 0.8914])
the box cls=
tensor(1)
the box max_prob
tensor(0.9974)
the box contain_prob
tensor([0.9979])
float((contain_prob*max_prob)[0])
0.9953446984291077
find a box (6 7 1)
cls_indexs_len=1
tensor([0])
[0]
[0]
1
get i: 0
index[0] ious=
tensor([], size=(1, 0))
[]
[0]
############## write file ./input/detection-results/361658066微信图片_202007152019001.txt##############
img name=week10_dataset/image/zhangyu/微信图片_202007150229589.jpg
pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor_h: tensor([[ 5.0000],
        [11.9688]])
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[6,6,1]==1
box.size: torch.Size([4])
get a box
tensor([ 0.

In [11]:
!python main.py

23.65% = 其他 AP 
66.67% = 农夫山泉 AP 
50.00% = 冰露 AP 
50.00% = 可口可乐 AP 
12.72% = 天府可乐 AP 
16.67% = 娃哈哈 AP 
0.00% = 康师傅 AP 
25.00% = 怡宝 AP 
33.33% = 苏打水 AP 
mAP = 30.89%
Figure(640x480)


In [2]:
!python train.py

conv1.weight
yes
bn1.weight
yes
bn1.bias
yes
bn1.running_mean
yes
bn1.running_var
yes
bn1.num_batches_tracked
yes
layer1.0.conv1.weight
yes
layer1.0.bn1.weight
yes
layer1.0.bn1.bias
yes
layer1.0.bn1.running_mean
yes
layer1.0.bn1.running_var
yes
layer1.0.bn1.num_batches_tracked
yes
layer1.0.conv2.weight
yes
layer1.0.bn2.weight
yes
layer1.0.bn2.bias
yes
layer1.0.bn2.running_mean
yes
layer1.0.bn2.running_var
yes
layer1.0.bn2.num_batches_tracked
yes
layer1.0.conv3.weight
yes
layer1.0.bn3.weight
yes
layer1.0.bn3.bias
yes
layer1.0.bn3.running_mean
yes
layer1.0.bn3.running_var
yes
layer1.0.bn3.num_batches_tracked
yes
layer1.0.downsample.0.weight
yes
layer1.0.downsample.1.weight
yes
layer1.0.downsample.1.bias
yes
layer1.0.downsample.1.running_mean
yes
layer1.0.downsample.1.running_var
yes
layer1.0.downsample.1.num_batches_tracked
yes
layer1.1.conv1.weight
yes
layer1.1.bn1.weight
yes
layer1.1.bn1.bias
yes
layer1.1.bn1.running_mean
yes
layer1.1.bn1.running_var
yes
layer1.1.bn1.num_batches_tracke

Epoch 1/200: 100%|█| 73/73 [01:20<00:00,  1.11s/it, average_loss=2.94e+3, loss_c
Epoch 2/200: 100%|█| 73/73 [01:20<00:00,  1.11s/it, average_loss=2.74e+3, loss_c
Epoch 3/200: 100%|█| 73/73 [01:21<00:00,  1.12s/it, average_loss=2.66e+3, loss_c
Epoch 4/200: 100%|█| 73/73 [01:22<00:00,  1.13s/it, average_loss=2.6e+3, loss_cl
Epoch 5/200: 100%|█| 73/73 [01:21<00:00,  1.12s/it, average_loss=2.53e+3, loss_c
Epoch 6/200: 100%|█| 73/73 [01:18<00:00,  1.08s/it, average_loss=2.45e+3, loss_c
Epoch 7/200: 100%|█| 73/73 [01:20<00:00,  1.11s/it, average_loss=2.38e+3, loss_c
Epoch 8/200: 100%|█| 73/73 [01:19<00:00,  1.09s/it, average_loss=2.32e+3, loss_c
Epoch 9/200: 100%|█| 73/73 [01:19<00:00,  1.09s/it, average_loss=2.27e+3, loss_c
Epoch 10/200: 100%|█| 73/73 [01:20<00:00,  1.10s/it, average_loss=2.21e+3, loss_
Epoch 11/200: 100%|█| 73/73 [01:20<00:00,  1.10s/it, average_loss=2.14e+3, loss_
Epoch 12/200: 100%|█| 73/73 [01:23<00:00,  1.15s/it, average_loss=2.08e+3, loss_
Epoch 13/200: 100%|█| 73/73 

Epoch 191/200: 100%|█| 73/73 [01:27<00:00,  1.20s/it, average_loss=0.42, loss_cl
Epoch 192/200: 100%|█| 73/73 [01:27<00:00,  1.19s/it, average_loss=0.389, loss_c
Epoch 193/200: 100%|█| 73/73 [01:27<00:00,  1.20s/it, average_loss=0.654, loss_c
Epoch 194/200: 100%|█| 73/73 [01:27<00:00,  1.19s/it, average_loss=0.427, loss_c
Epoch 195/200: 100%|█| 73/73 [01:28<00:00,  1.21s/it, average_loss=0.383, loss_c
get best test loss 0.38337
Epoch 196/200: 100%|█| 73/73 [01:27<00:00,  1.21s/it, average_loss=0.385, loss_c
Epoch 197/200: 100%|█| 73/73 [01:28<00:00,  1.21s/it, average_loss=0.424, loss_c
Epoch 198/200: 100%|█| 73/73 [01:27<00:00,  1.19s/it, average_loss=0.466, loss_c
Epoch 199/200: 100%|█| 73/73 [01:27<00:00,  1.19s/it, average_loss=0.376, loss_c
get best test loss 0.37648
Epoch 200/200: 100%|█| 73/73 [01:26<00:00,  1.19s/it, average_loss=0.401, loss_c
train.py:227: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  img = Variable(img[None, :

pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor_h: tensor([[ 5.0000],
        [11.9688]])
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[6,7,1]==1
box.size: torch.Size([4])
get a box
tensor([0.4432, 0.0982, 0.6575, 0.8782])
the box cls=
tensor(6)
the box max_prob
tensor(0.3075)
the box contain_prob
tensor([0.3692])
float((contain_prob*max_prob)[0])
0.11352383345365524
find a box (6 7 1)
mask[7,5,1]==1
box.size: torch.Size([4])
get a box
tensor([0.2425, 0.0832, 0.5135, 0.9574])
the box cls=
tensor(6)
the box max_prob
tensor(0.0120)
the box contain_prob
tensor([0.8999])
float((contain_prob*max_prob)[0])
0.010777714662253857
contain_prob*max_prob not > 0.02
mask[7,8,1]==1
box.size: torch.Size([4])
get a box
tensor([0.4708, 0.0618, 0.7508, 0.9482])
the box cls=
tensor(13)
the box max_prob
tensor(0.9993)
the box contain_prob
tensor([0.5138])
float((contain_prob*max_prob)[0])
0.5133945345878601
find a box (7 8 1)

pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor_h: tensor([[ 5.0000],
        [11.9688]])
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[6,7,1]==1
box.size: torch.Size([4])
get a box
tensor([0.3964, 0.0585, 0.6299, 0.9338])
the box cls=
tensor(13)
the box max_prob
tensor(0.9998)
the box contain_prob
tensor([0.0716])
float((contain_prob*max_prob)[0])
0.07158005982637405
find a box (6 7 1)
cls_indexs_len=1
tensor([0])
[0]
[0]
1
get i: 0
index[0] ious=
tensor([], size=(1, 0))
[]
[0]
pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor_h: tensor([[ 5.0000],
        [11.9688]])
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[6,6,1]==1
box.size: torch.Size([4])
get a box
tensor([0.3218, 0.0499, 0.6233, 0.9145])
the box cls=
tensor(13)
the box max_prob
tensor(0.9510)
the box contain_prob
tensor([1.0000])
float((contain_prob*max_prob)[0])
0.9

In [9]:
!python predict_decoder.py

img name=week10_dataset/image/guozhiwei/7.jpg
predict_decoder.py:266: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  img = Variable(img[None, :, :, :], volatile=True)
pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor_h: tensor([[ 5.0000],
        [11.9688]])
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[7,7,1]==1
box.size: torch.Size([4])
get a box
tensor([0.3240, 0.1072, 0.6953, 0.9039])
the box cls=
tensor(7)
the box max_prob
tensor(0.0111)
the box contain_prob
tensor([0.5067])
float((contain_prob*max_prob)[0])
0.005628562066704035
contain_prob*max_prob not > 0.02
tensor([0])
[0]
[0]
1
get i: 0
index[0] ious=
tensor([], size=(1, 0))
[]
[0]
############## write file ./input/detection-results/guozhiwei7.txt##############
img name=week10_dataset/image/guozhiwei/8.jpg
pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor_h:

pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor_h: tensor([[ 5.0000],
        [11.9688]])
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[9,4,1]==1
box.size: torch.Size([4])
get a box
tensor([0.2170, 0.3053, 0.4615, 1.0281])
the box cls=
tensor(11)
the box max_prob
tensor(0.8858)
the box contain_prob
tensor([0.5689])
float((contain_prob*max_prob)[0])
0.5039356350898743
find a box (9 4 1)
cls_indexs_len=1
tensor([0])
[0]
[0]
1
get i: 0
index[0] ious=
tensor([], size=(1, 0))
[]
[0]
############## write file ./input/detection-results/zhaomingmingWechatIMG417.txt##############
img name=week10_dataset/image/zhaomingming/WechatIMG413.png
pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor_h: tensor([[ 5.0000],
        [11.9688]])
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[6,7,1]==1
box.size: torch.Size([4])
get a box
tensor([0.4431, 0.

pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor_h: tensor([[ 5.0000],
        [11.9688]])
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[8,3,1]==1
box.size: torch.Size([4])
get a box
tensor([0.1689, 0.1512, 0.3963, 1.0138])
the box cls=
tensor(9)
the box max_prob
tensor(0.9879)
the box contain_prob
tensor([0.9114])
float((contain_prob*max_prob)[0])
0.9004195332527161
find a box (8 3 1)
cls_indexs_len=1
tensor([0])
[0]
[0]
1
get i: 0
index[0] ious=
tensor([], size=(1, 0))
[]
[0]
############## write file ./input/detection-results/zhaomingmingWechatIMG408.txt##############
img name=week10_dataset/image/zhaomingming/WechatIMG386.png
pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor_h: tensor([[ 5.0000],
        [11.9688]])
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[6,10,1]==1
box.size: torch.Size([4])
get a box
tensor([0.6123, 0.

pred.size: torch.Size([1, 14, 14, 24])
anchor_w: tensor([[0.8750],
        [4.2812]])
anchor_h: tensor([[ 5.0000],
        [11.9688]])
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[6,6,1]==1
box.size: torch.Size([4])
get a box
tensor([0.2660, 0.0790, 0.6333, 0.8992])
the box cls=
tensor(6)
the box max_prob
tensor(0.2670)
the box contain_prob
tensor([0.9745])
float((contain_prob*max_prob)[0])
0.2601941227912903
find a box (6 6 1)
mask[7,2,1]==1
box.size: torch.Size([4])
get a box
tensor([0.1032, 0.0763, 0.3078, 0.9581])
the box cls=
tensor(13)
the box max_prob
tensor(0.6638)
the box contain_prob
tensor([0.3990])
float((contain_prob*max_prob)[0])
0.2648318409919739
find a box (7 2 1)
cls_indexs_len=2
tensor([1, 0])
[1 0]
[1 0]
2
get i: 1
index[1] ious=
tensor([[0.0765]])
[0]
get i: 0
index[0] ious=
tensor([], size=(1, 0))
[]
[1, 0]
############## write file ./input/detection-results/361658066微信图片_202007152018597.txt##############
img name=week10_datase

In [10]:
!python main.py

4.17% = 其他 AP 
83.33% = 农夫山泉 AP 
50.00% = 冰露 AP 
50.00% = 可口可乐 AP 
7.89% = 天府可乐 AP 
13.89% = 娃哈哈 AP 
0.00% = 康师傅 AP 
0.00% = 怡宝 AP 
0.00% = 苏打水 AP 
mAP = 23.25%
Figure(640x480)


In [1]:
!python train.py

conv1.weight
yes
bn1.weight
yes
bn1.bias
yes
bn1.running_mean
yes
bn1.running_var
yes
bn1.num_batches_tracked
yes
layer1.0.conv1.weight
yes
layer1.0.bn1.weight
yes
layer1.0.bn1.bias
yes
layer1.0.bn1.running_mean
yes
layer1.0.bn1.running_var
yes
layer1.0.bn1.num_batches_tracked
yes
layer1.0.conv2.weight
yes
layer1.0.bn2.weight
yes
layer1.0.bn2.bias
yes
layer1.0.bn2.running_mean
yes
layer1.0.bn2.running_var
yes
layer1.0.bn2.num_batches_tracked
yes
layer1.0.conv3.weight
yes
layer1.0.bn3.weight
yes
layer1.0.bn3.bias
yes
layer1.0.bn3.running_mean
yes
layer1.0.bn3.running_var
yes
layer1.0.bn3.num_batches_tracked
yes
layer1.0.downsample.0.weight
yes
layer1.0.downsample.1.weight
yes
layer1.0.downsample.1.bias
yes
layer1.0.downsample.1.running_mean
yes
layer1.0.downsample.1.running_var
yes
layer1.0.downsample.1.num_batches_tracked
yes
layer1.1.conv1.weight
yes
layer1.1.bn1.weight
yes
layer1.1.bn1.bias
yes
layer1.1.bn1.running_mean
yes
layer1.1.bn1.running_var
yes
layer1.1.bn1.num_batches_tracke

Epoch 1/130: 100%|█| 73/73 [13:14<00:00, 10.88s/it, average_loss=949, loss_cls=8
Epoch 2/130: 100%|█| 73/73 [12:42<00:00, 10.45s/it, average_loss=898, loss_cls=2
Epoch 3/130: 100%|█| 73/73 [09:30<00:00,  7.82s/it, average_loss=866, loss_cls=5
Epoch 4/130: 100%|█| 73/73 [05:02<00:00,  4.14s/it, average_loss=850, loss_cls=1
Epoch 5/130: 100%|█| 73/73 [03:27<00:00,  2.85s/it, average_loss=834, loss_cls=3
Epoch 6/130: 100%|█| 73/73 [04:13<00:00,  3.47s/it, average_loss=825, loss_cls=1
Epoch 7/130: 100%|█| 73/73 [05:03<00:00,  4.16s/it, average_loss=822, loss_cls=7
Epoch 8/130: 100%|█| 73/73 [04:54<00:00,  4.03s/it, average_loss=813, loss_cls=7
Epoch 9/130: 100%|█| 73/73 [04:56<00:00,  4.06s/it, average_loss=808, loss_cls=3
Epoch 10/130: 100%|█| 73/73 [05:10<00:00,  4.26s/it, average_loss=806, loss_cls=
Epoch 11/130: 100%|█| 73/73 [04:49<00:00,  3.97s/it, average_loss=798, loss_cls=
Epoch 12/130: 100%|█| 73/73 [05:07<00:00,  4.21s/it, average_loss=791, loss_cls=
Epoch 13/130: 100%|█| 73/73 

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



Epoch 111/130: 100%|█| 73/73 [01:30<00:00,  1.25s/it, average_loss=17.2, loss_cl
++++++Start Validation++++++
Epoch 111/130: 100%|█| 18/18 [00:11<00:00,  1.61it/s, loss_cls=3.16, loss_conf=1
Finish Validation
Epoch:111/130
++++++Train Loss: 17.1713 || Val Loss: 70.1124 ++++++

Epoch 112/130: 100%|█| 73/73 [01:31<00:00,  1.25s/it, average_loss=17.2, loss_cl
++++++Start Validation++++++
Epoch 112/130: 100%|█| 18/18 [00:11<00:00,  1.60it/s, loss_cls=3.62, loss_conf=2
Finish Validation
Epoch:112/130
++++++Train Loss: 17.2460 || Val Loss: 70.4707 ++++++

Epoch 113/130: 100%|█| 73/73 [01:32<00:00,  1.27s/it, average_loss=16.1, loss_cl
get best train loss 16.11757
++++++Start Validation++++++
Epoch 113/130: 100%|█| 18/18 [00:10<00:00,  1.64it/s, loss_cls=3.19, loss_conf=2
Finish Validation
Epoch:113/130
++++++Train Loss: 16.1176 || Val Loss: 70.9295 ++++++

Epoch 114/130: 100%|█| 73/73 [01:33<00:00,  1.28s/it, average_loss=16.3, loss_cl
++++++Start Validation++++++
Epoch 114/130: 100%|█| 18/1

pred.size: torch.Size([1, 14, 14, 24])
anchor_w: [0.875, 5.0]
anchor_h: [4.28125, 11.96875]
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[9,7,1]==1
box.size: torch.Size([4])
get a box
tensor([0.1563, 0.4662, 0.9084, 0.8490])
the box cls=
tensor(10)
the box max_prob
tensor(0.6907)
the box contain_prob
tensor([0.1978])
float((contain_prob*max_prob)[0])
0.13663241267204285
find a box (9 7 1)
cls_indexs_len=1
tensor([0])
[0]
[0]
1
get i: 0
index[0] ious=
tensor([], size=(1, 0))
[]
[0]
pred.size: torch.Size([1, 14, 14, 24])
anchor_w: [0.875, 5.0]
anchor_h: [4.28125, 11.96875]
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[7,9,1]==1
box.size: torch.Size([4])
get a box
tensor([0.4636, 0.2304, 0.9003, 0.8211])
the box cls=
tensor(10)
the box max_prob
tensor(0.6209)
the box contain_prob
tensor([0.0644])
float((contain_prob*max_prob)[0])
0.03996684029698372
find a box (7 9 1)
cls_indexs_len=1
tensor([0])
[0]
[0]
1
get i: 0
in

pred.size: torch.Size([1, 14, 14, 24])
anchor_w: [0.875, 5.0]
anchor_h: [4.28125, 11.96875]
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[6,7,1]==1
box.size: torch.Size([4])
get a box
tensor([0.1685, 0.2704, 0.8931, 0.6865])
the box cls=
tensor(13)
the box max_prob
tensor(0.9239)
the box contain_prob
tensor([0.3151])
float((contain_prob*max_prob)[0])
0.2910836338996887
find a box (6 7 1)
mask[7,10,1]==1
box.size: torch.Size([4])
get a box
tensor([0.6385, 0.0194, 0.8503, 1.0295])
the box cls=
tensor(13)
the box max_prob
tensor(0.6548)
the box contain_prob
tensor([0.3090])
float((contain_prob*max_prob)[0])
0.2023460566997528
find a box (7 10 1)
cls_indexs_len=2
tensor([0, 1])
[0 1]
[0 1]
2
get i: 0
index[0] ious=
tensor([[0.2062]])
[0]
get i: 1
index[1] ious=
tensor([], size=(1, 0))
[]
[0, 1]
pred.size: torch.Size([1, 14, 14, 24])
anchor_w: [0.875, 5.0]
anchor_h: [4.28125, 11.96875]
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14

pred.size: torch.Size([1, 14, 14, 24])
anchor_w: [0.875, 5.0]
anchor_h: [4.28125, 11.96875]
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[6,8,1]==1
box.size: torch.Size([4])
get a box
tensor([0.3939, 0.1160, 0.7822, 0.8266])
the box cls=
tensor(11)
the box max_prob
tensor(0.9992)
the box contain_prob
tensor([0.1648])
float((contain_prob*max_prob)[0])
0.16471634805202484
find a box (6 8 1)
cls_indexs_len=1
tensor([0])
[0]
[0]
1
get i: 0
index[0] ious=
tensor([], size=(1, 0))
[]
[0]
pred.size: torch.Size([1, 14, 14, 24])
anchor_w: [0.875, 5.0]
anchor_h: [4.28125, 11.96875]
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[6,7,1]==1
box.size: torch.Size([4])
get a box
tensor([0.3526, 0.0091, 0.6698, 0.9353])
the box cls=
tensor(11)
the box max_prob
tensor(0.9999)
the box contain_prob
tensor([0.8306])
float((contain_prob*max_prob)[0])
0.8305038213729858
find a box (6 7 1)
cls_indexs_len=1
tensor([0])
[0]
[0]
1
get i: 0
ind

In [2]:
!python predict_decoder.py
!python main.py

img name=week10_dataset/image/guozhiwei/7.jpg
predict_decoder.py:268: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  img = Variable(img[None, :, :, :], volatile=True)
pred.size: torch.Size([1, 14, 14, 24])
anchor_w: [0.875, 5.0]
anchor_h: [4.28125, 11.96875]
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[6,7,1]==1
box.size: torch.Size([4])
get a box
tensor([0.2209, 0.1982, 0.8471, 0.7727])
the box cls=
tensor(3)
the box max_prob
tensor(0.2215)
the box contain_prob
tensor([0.6540])
float((contain_prob*max_prob)[0])
0.14489144086837769
find a box (6 7 1)
mask[7,7,1]==1
box.size: torch.Size([4])
get a box
tensor([0.1583, 0.3121, 0.9038, 0.7382])
the box cls=
tensor(3)
the box max_prob
tensor(0.4876)
the box contain_prob
tensor([0.7255])
float((contain_prob*max_prob)[0])
0.3537765443325043
find a box (7 7 1)
cls_indexs_len=2
tensor([1, 0])
[1 0]
[1 0]
2
get i: 1
index[1] ious=
tensor([[0.6499]])
[]
[1]
####

pred.size: torch.Size([1, 14, 14, 24])
anchor_w: [0.875, 5.0]
anchor_h: [4.28125, 11.96875]
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[7,6,1]==1
box.size: torch.Size([4])
get a box
tensor([0.1268, 0.2868, 0.8413, 0.7467])
the box cls=
tensor(9)
the box max_prob
tensor(0.2305)
the box contain_prob
tensor([0.5736])
float((contain_prob*max_prob)[0])
0.13219717144966125
find a box (7 6 1)
mask[7,7,1]==1
box.size: torch.Size([4])
get a box
tensor([0.1075, 0.3571, 0.9273, 0.6820])
the box cls=
tensor(10)
the box max_prob
tensor(0.2490)
the box contain_prob
tensor([0.5068])
float((contain_prob*max_prob)[0])
0.12619389593601227
find a box (7 7 1)
cls_indexs_len=2
tensor([0, 1])
[0 1]
[0 1]
2
get i: 0
index[0] ious=
tensor([[0.6397]])
[]
[0]
############## write file ./input/detection-results/zhaomingmingWechatIMG385.txt##############
img name=week10_dataset/image/zhaomingming/WechatIMG417.png
pred.size: torch.Size([1, 14, 14, 24])
anchor_w: [0.875, 5.0]
a

pred.size: torch.Size([1, 14, 14, 24])
anchor_w: [0.875, 5.0]
anchor_h: [4.28125, 11.96875]
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[7,3,1]==1
box.size: torch.Size([4])
get a box
tensor([0.1221, 0.1115, 0.4204, 0.9748])
the box cls=
tensor(9)
the box max_prob
tensor(0.8867)
the box contain_prob
tensor([0.7323])
float((contain_prob*max_prob)[0])
0.6493123173713684
find a box (7 3 1)
mask[8,3,1]==1
box.size: torch.Size([4])
get a box
tensor([0.1478, 0.0838, 0.3953, 1.0999])
the box cls=
tensor(9)
the box max_prob
tensor(0.9589)
the box contain_prob
tensor([0.7715])
float((contain_prob*max_prob)[0])
0.7398065328598022
find a box (8 3 1)
cls_indexs_len=2
tensor([1, 0])
[1 0]
[1 0]
2
get i: 1
index[1] ious=
tensor([[0.7234]])
[]
[1]
############## write file ./input/detection-results/zhaomingmingWechatIMG408.txt##############
img name=week10_dataset/image/zhaomingming/WechatIMG386.png
pred.size: torch.Size([1, 14, 14, 24])
anchor_w: [0.875, 5.0]
anch

pred.size: torch.Size([1, 14, 14, 24])
anchor_w: [0.875, 5.0]
anchor_h: [4.28125, 11.96875]
pred.size:  torch.Size([1, 14, 14, 24])
pred.size:  torch.Size([14, 14, 24])
mask[6,6,1]==1
box.size: torch.Size([4])
get a box
tensor([0.2708, 0.0025, 0.6799, 0.9403])
the box cls=
tensor(11)
the box max_prob
tensor(0.9983)
the box contain_prob
tensor([0.6833])
float((contain_prob*max_prob)[0])
0.6821290850639343
find a box (6 6 1)
mask[6,7,1]==1
box.size: torch.Size([4])
get a box
tensor([0.3360, 0.0231, 0.6852, 0.9222])
the box cls=
tensor(11)
the box max_prob
tensor(0.9987)
the box contain_prob
tensor([0.8155])
float((contain_prob*max_prob)[0])
0.8144347071647644
find a box (6 7 1)
mask[7,7,1]==1
box.size: torch.Size([4])
get a box
tensor([0.3059, 0.0974, 0.7238, 0.9376])
the box cls=
tensor(11)
the box max_prob
tensor(0.9233)
the box contain_prob
tensor([0.3721])
float((contain_prob*max_prob)[0])
0.3435446619987488
find a box (7 7 1)
cls_indexs_len=3
tensor([1, 0, 2])
[1 0 2]
[1 0 2]
3
get 

In [11]:
import numpy as np
ious = [[0.8, 0.7, 1, 6, 4],[0.8, 0.7, 1, 6, 4]]
ious = np.array(ious)
print(ious.shape)
threshold =1
idx = np.where(ious <= threshold)[1]
print( idx)

(2, 5)
[0 1 2 0 1 2]


In [18]:
idx = np.max(ious,axis=0)
print(idx)

[0.8 0.7 1.  6.  4. ]


In [21]:
import torch
a = torch.tensor([[1,5,62,54], [2,6,2,6]])
b = torch.max(a, 0)
print(b)

torch.return_types.max(
values=tensor([ 2,  6, 62, 54]),
indices=tensor([1, 1, 0, 0]))


In [4]:
!python train.py

conv1.weight
yes
bn1.weight
yes
bn1.bias
yes
bn1.running_mean
yes
bn1.running_var
yes
bn1.num_batches_tracked
yes
layer1.0.conv1.weight
yes
layer1.0.bn1.weight
yes
layer1.0.bn1.bias
yes
layer1.0.bn1.running_mean
yes
layer1.0.bn1.running_var
yes
layer1.0.bn1.num_batches_tracked
yes
layer1.0.conv2.weight
yes
layer1.0.bn2.weight
yes
layer1.0.bn2.bias
yes
layer1.0.bn2.running_mean
yes
layer1.0.bn2.running_var
yes
layer1.0.bn2.num_batches_tracked
yes
layer1.0.conv3.weight
yes
layer1.0.bn3.weight
yes
layer1.0.bn3.bias
yes
layer1.0.bn3.running_mean
yes
layer1.0.bn3.running_var
yes
layer1.0.bn3.num_batches_tracked
yes
layer1.0.downsample.0.weight
yes
layer1.0.downsample.1.weight
yes
layer1.0.downsample.1.bias
yes
layer1.0.downsample.1.running_mean
yes
layer1.0.downsample.1.running_var
yes
layer1.0.downsample.1.num_batches_tracked
yes
layer1.1.conv1.weight
yes
layer1.1.bn1.weight
yes
layer1.1.bn1.bias
yes
layer1.1.bn1.running_mean
yes
layer1.1.bn1.running_var
yes
layer1.1.bn1.num_batches_tracke

Epoch 1/200: 100%|█| 73/73 [02:14<00:00,  1.84s/it, loss_conf=306, loss_loc=0.83
Epoch 2/200: 100%|█| 73/73 [02:16<00:00,  1.87s/it, loss_conf=288, loss_loc=2.1,
Epoch 3/200: 100%|█| 73/73 [02:10<00:00,  1.79s/it, loss_conf=281, loss_loc=0.64
Epoch 4/200: 100%|█| 73/73 [01:57<00:00,  1.61s/it, loss_conf=280, loss_loc=0.99
Epoch 5/200: 100%|█| 73/73 [02:01<00:00,  1.66s/it, loss_conf=281, loss_loc=0.74
Epoch 6/200: 100%|█| 73/73 [01:53<00:00,  1.55s/it, loss_conf=278, loss_loc=0.82
Epoch 7/200: 100%|█| 73/73 [01:56<00:00,  1.59s/it, loss_conf=273, loss_loc=0.78
Epoch 8/200: 100%|█| 73/73 [02:14<00:00,  1.84s/it, loss_conf=267, loss_loc=0.69
Epoch 9/200: 100%|█| 73/73 [02:24<00:00,  1.97s/it, loss_conf=267, loss_loc=0.45
Epoch 10/200: 100%|█| 73/73 [02:17<00:00,  1.88s/it, loss_conf=269, loss_loc=0.7
get best train loss 817.04114
Epoch 11/200: 100%|█| 73/73 [02:17<00:00,  1.88s/it, loss_conf=209, loss_loc=0.7
get best train loss 731.10927
++++++Start Validation++++++
Epoch 11/200: 100%|█

Epoch 28/200: 100%|█| 18/18 [00:13<00:00,  1.29it/s, loss_cls=3.51, loss_conf=6.
Finish Validation
Epoch:28/200
++++++Train Loss: 35.5762 || Val Loss: 67.8385 ++++++
Saving state, iter: 28
get best test loss 67.83851

Epoch 29/200: 100%|█| 73/73 [01:52<00:00,  1.54s/it, loss_conf=11.6, loss_loc=1.
get best train loss 33.27439
++++++Start Validation++++++
Epoch 29/200: 100%|█| 18/18 [00:14<00:00,  1.27it/s, loss_cls=3.69, loss_conf=5.
Finish Validation
Epoch:29/200
++++++Train Loss: 33.2744 || Val Loss: 112.5928 ++++++

Epoch 30/200: 100%|█| 73/73 [02:14<00:00,  1.84s/it, loss_conf=5.09, loss_loc=0.
get best train loss 31.72880
++++++Start Validation++++++
Epoch 30/200: 100%|█| 18/18 [00:15<00:00,  1.14it/s, loss_cls=3.45, loss_conf=5.
Finish Validation
Epoch:30/200
++++++Train Loss: 31.7288 || Val Loss: 90.5977 ++++++

Epoch 31/200: 100%|█| 73/73 [02:13<00:00,  1.83s/it, loss_conf=7.99, loss_loc=0.
get best train loss 30.99638
++++++Start Validation++++++
Epoch 31/200: 100%|█| 18/18 [0

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



Epoch 121/200: 100%|█| 73/73 [01:28<00:00,  1.21s/it, loss_conf=2.7, loss_loc=0.
++++++Start Validation++++++
Epoch 121/200: 100%|█| 18/18 [00:10<00:00,  1.65it/s, loss_cls=3.29, loss_conf=2
Finish Validation
Epoch:121/200
++++++Train Loss: 20.9881 || Val Loss: 66.2730 ++++++

Epoch 122/200: 100%|█| 73/73 [01:30<00:00,  1.23s/it, loss_conf=3.3, loss_loc=0.
++++++Start Validation++++++
Epoch 122/200: 100%|█| 18/18 [00:10<00:00,  1.65it/s, loss_cls=3.42, loss_conf=2
Finish Validation
Epoch:122/200
++++++Train Loss: 20.7508 || Val Loss: 65.8089 ++++++

Epoch 123/200: 100%|█| 73/73 [01:28<00:00,  1.22s/it, loss_conf=3.02, loss_loc=0
get best train loss 20.56880
++++++Start Validation++++++
Epoch 123/200: 100%|█| 18/18 [00:10<00:00,  1.73it/s, loss_cls=3.35, loss_conf=2
Finish Validation
Epoch:123/200
++++++Train Loss: 20.5688 || Val Loss: 66.3507 ++++++

Epoch 124/200: 100%|█| 73/73 [01:31<00:00,  1.25s/it, loss_conf=5.77, loss_loc=0
++++++Start Validation++++++
Epoch 124/200: 100%|█| 18/1

Epoch 145/200: 100%|█| 73/73 [01:31<00:00,  1.26s/it, loss_conf=12.1, loss_loc=1
++++++Start Validation++++++
Epoch 145/200: 100%|█| 18/18 [00:10<00:00,  1.71it/s, loss_cls=3.46, loss_conf=2
Finish Validation
Epoch:145/200
++++++Train Loss: 20.3764 || Val Loss: 69.5239 ++++++

Epoch 146/200: 100%|█| 73/73 [01:32<00:00,  1.26s/it, loss_conf=3.61, loss_loc=0
++++++Start Validation++++++
Epoch 146/200: 100%|█| 18/18 [00:10<00:00,  1.66it/s, loss_cls=3.36, loss_conf=2
Finish Validation
Epoch:146/200
++++++Train Loss: 20.9964 || Val Loss: 65.5877 ++++++

Epoch 147/200: 100%|█| 73/73 [01:32<00:00,  1.27s/it, loss_conf=4.93, loss_loc=0
++++++Start Validation++++++
Epoch 147/200: 100%|█| 18/18 [00:10<00:00,  1.69it/s, loss_cls=3.31, loss_conf=2
Finish Validation
Epoch:147/200
++++++Train Loss: 20.8430 || Val Loss: 66.8147 ++++++

Epoch 148/200: 100%|█| 73/73 [01:33<00:00,  1.28s/it, loss_conf=9.31, loss_loc=1
++++++Start Validation++++++
Epoch 148/200: 100%|█| 18/18 [00:10<00:00,  1.77it/s, lo

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:
!python predict_decoder.py
!python main.py